MODEL:
  #META_ARCHITECTURE: "GeneralizedRCNN"
  META_ARCHITECTURE: "VGRCNN"
  #WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  WEIGHT: "models/pretrain/x152.pth"
  BACKBONE:
    CONV_BODY: "R-152-FPN"
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    BATCH_SIZE_PER_IMAGE: 512
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 1601
    MLP_HEAD_DIM: 2048
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1

DATASETS:
  TRAIN: ("vg_train", "vg_val")
  TEST: ("vg_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  #BASE_LR: 0.04
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  #STEPS: (60000, 80000)
  MAX_ITER: 360000
  #MAX_ITER: 90000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (600, 700, 800, 900, 1000)
  MAX_SIZE_TRAIN: 1600
OUTPUT_DIR: "models/x152_vg_attr_mdconv_ms"
