MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrain/X-101-GN-WS.pkl"
  CASCADE_ON: True
  CLS_AGNOSTIC_BBOX_REG: True
  BACKBONE:
    CONV_BODY: "R-101-NASFPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    TRANS_FUNC: "BottleneckWithGN"
    STEM_FUNC: "StemWithGN"
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 4
  FPN:
    NAS_NUM: 7
    USE_GN: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    USE_GN: True
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPNXconv1fcFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    SEMANTIC_POOLER_SCALES: (0.125, )
  ROI_MASK_HEAD:
    USE_GN: True
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    INTERLEAVED_EXECUTION: True
    INFORMATION_FLOW: True
    SEMANTIC_POOLER_SCALES: (0.125, )
  SEMANTIC_HEAD:
    CONV_CHANNELS: 256
    USE_GN: True
    NUM_INS: 5
    FUSION_LEVEL: 1
    NUM_CLASSES: 183
  MASK_ON: True
  SEMANTIC_ON: True
  USE_WS: True
DATASETS:
  TRAIN: ("coco_2017_train_stuff", )
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (360000, 480000)
  MAX_ITER: 540000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: "models/cascade_mask_x_101_nasfpn_mdconv_gn_ws_ie_if_sf_2017_3x"
